### ISSUE TITLE
is it possible to add a button with action as a custom view?

### ISSUE THREAD

**Issue by rinat-enikeev** [waizeiaifu/EmptyDataSet-Swift#13]
I can't get action called with the following code: 

    func customView(forEmptyDataSet scrollView: UIScrollView) -> UIView? {
        let button = UIButton(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
        button.addTarget(self, action: #selector(hello), for: [.touchUpInside])
        button.backgroundColor = UIColor.red
        return button
    }
    
    @objc func hello() {
        print("Hello")
    }

**Comment by waizeiaifu** [comment]
I have fixed it in 4.0.5

**Comment by trungld123** [comment]
how to fix it? @Xiaoye220
