### ISSUE TITLE
Incorrect object sent to emptyDataSet(:didTapView:) delegate method

### ISSUE THREAD

**Issue by m3g0byt3** [waizeiaifu/EmptyDataSet-Swift#14]
In the `emptyDataSet(:didTapView:) ` method of `EmptyDataSetDelegate` instead of `UIView` instance tapped by the user (as description says) - a `UITapGestureRecognizer` instance passed:

![screenshot 2018-06-08 19 27 01](https://user-images.githubusercontent.com/21194149/41169534-fccb6f26-6b51-11e8-9939-3c7011e6a07d.png)

**Comment by waizeiaifu** [comment]
thanks

**Comment by m3g0byt3** [comment]
👍
