### ISSUE TITLE
emptyDataSetView is not showing correctly when contentInset is set

### ISSUE THREAD

**Issue by highjump0615** [waizeiaifu/EmptyDataSet-Swift#16]
When contentInset is set for left and right, only left offset is working..
As a result, empty label cannot be centered horizontally.
Below is the code snippet and its screenshot
```swift
mCollectionView.contentInset = UIEdgeInsets(top: 0,
                                            left: 50,
                                            bottom: 0,
                                            right: 50)
mCollectionView.backgroundColor = UIColor.red

mCollectionView.emptyDataSetView { (view) in
    view.titleLabelString(Utils.getAttributedString(text: "No photos uploaded yet"))
        .backgroundColor = UIColor.yellow
}
```

<img src="https://user-images.githubusercontent.com/19966744/41871871-cbcdc58c-78f2-11e8-860c-bcc6220adeeb.png" width="300" />

**Comment by waizeiaifu** [comment]
maybe you can set contentInset with UIEdgeInsets(top: 0, left: 50,  bottom: 0, right: -50)

**Comment by mdilaveroglu** [comment]
This problem still continues.

**Comment by highjump0615** [comment]
Yes, I think this issue can be fixed, I will try to make pr when I have time.
