### ISSUE TITLE
初始化设置了代理

### ISSUE THREAD

**Issue by zhufaming** [waizeiaifu/EmptyDataSet-Swift#23]
加载数据成功前都会先处理占位闪一下

**Comment by waizeiaifu** [comment]
能请问一下具体是怎么操作，我测试一下

**Comment by zhufaming** [comment]
viewdidload 里面初始化tableView 设置代理
然后前期数据、数据成功后，调用reload()
本来有数据，然后空置图会闪动一下，然后显示数据源

**Comment by zhufaming** [comment]
现在的解决方案是，数据请求成功后，数组为空，再设置的代理

**Comment by waizeiaifu** [comment]
我测试后好像没有发现这个问题，是原来有数据，请求后还是有数据，但是空置图会闪一下？
