### ISSUE TITLE
有header 设置偏移量后

### ISSUE THREAD

**Issue by zhufaming** [waizeiaifu/EmptyDataSet-Swift#24]
大小被裁掉了，显示不完整

**Comment by waizeiaifu** [comment]
有没有 header 空置图都是占据整个 tableView 大小（也就是包括 header），因此设置偏移量需要把 header 的高度计算在内
```swift
func verticalOffset(forEmptyDataSet scrollView: UIScrollView) -> CGFloat {
    let headerHeight = tableView.tableHeaderView?.frame.size.height
    return headerHeight! / 2
}
```
上面的偏移量会使空置图处于 tableView 除去 header 的部分的正中间

**Comment by Catplantist** [comment]
请问一下为什么是 `return headerHeight! / 2` 而不是 `return headerHeight!` 呢？ @Xiaoye220

**Comment by waizeiaifu** [comment]
> 请问一下为什么是 `return headerHeight! / 2` 而不是 `return headerHeight!` 呢？ @Xiaoye220

就是一个数学计算的问题，画画图很容易看出来的，要讲道理我还真不知道怎么讲

**Comment by Catplantist** [comment]
> > 请问一下为什么是 `return headerHeight! / 2` 而不是 `return headerHeight!` 呢？ @Xiaoye220
> 
> 就是一个数学计算的问题，画画图很容易看出来的，要讲道理我还真不知道怎么讲

理解了，`header 空置图都是占据整个 tableView 大小（也就是包括 header）`，所以要 / 2才能居中，另外一半是分给 Bottom 的。谢谢
