### ISSUE TITLE
offset为0,但是缺省视图却不是垂直居中

### ISSUE THREAD

**Issue by AmadeusSys** [waizeiaifu/EmptyDataSet-Swift#25]
![image](https://user-images.githubusercontent.com/25811397/49277846-f880ff80-f4bd-11e8-8c3a-6d93c3289f06.png)

**Comment by xiaoyao20084321** [comment]
我的也没有居中。。。你咋解决的

**Comment by deepindo** [comment]
似乎没有人处理？
