### ISSUE TITLE
设置section的数量 但是row 的数量为零的时候  一直显示

### ISSUE THREAD

**Issue by FunnyerFeng** [waizeiaifu/EmptyDataSet-Swift#26]
设置section的数量 但是row 的数量为零的时候  一直显示

**Comment by waizeiaifu** [comment]
不是很清楚什么意思，row 为 0，显示不是正常的吗

**Comment by zakicheung** [comment]
应该某些section折叠场景，section存在section header，但是section下的row数量为0，因次会显示empty视图。
需要自己实现emptyDataSetShouldDisplay，进行处理，确实比较麻烦。
