### ISSUE TITLE
pod 'EmptyDataSet-Swift', '~> 4.2.0' not available 

### ISSUE THREAD

**Issue by muhammadfaheem-pycom** [waizeiaifu/EmptyDataSet-Swift#32]
according to instructions version, 4.2.0 is available but I am not able to install it with this version.

```[!] CocoaPods could not find compatible versions for pod "EmptyDataSet-Swift":
  In Podfile:
    EmptyDataSet-Swift (~> 4.2.0)

None of your spec sources contain a spec satisfying the dependency: `EmptyDataSet-Swift (~> 4.2.0)`.```

**Comment by waizeiaifu** [comment]
I can find `EmptyDataSet-Swift (~> 4.2.0)` in CocoaPods. Maybe you could update your cocoapods repo.
![WX20190701-151532](https://user-images.githubusercontent.com/17470805/60417568-53750380-9c13-11e9-8fa0-9887fb03819b.png)
