### ISSUE TITLE
No support for Gif images

### ISSUE THREAD

**Issue by 1AhmedYasser** [waizeiaifu/EmptyDataSet-Swift#36]
When trying to use gif images it just shows a blank white background

**Comment by waizeiaifu** [comment]
I'm sorry to be so late in dealing with this issue. The default value of emptyDataSetShouldAnimateImageView is false. You can overwrite this function and return true, animated images will work.

```swift
public extension EmptyDataSetDelegate {
    func emptyDataSetShouldAnimateImageView(_ scrollView: UIScrollView) -> Bool {
        return false
    }
}
```
