### ISSUE TITLE
remove tableview lines

### ISSUE THREAD

**Issue by ogezue** [waizeiaifu/EmptyDataSet-Swift#5]
Is it possible to remove the table view lines by your framework? Currently the label is renderd on top of the empty tableview. I would prefer a setting where your framework would hide the empty tableview. Perhaps you already have this option but I couldn't find it. Thanks

<img width="368" alt="bildschirmfoto 2017-12-14 um 08 34 53" src="https://user-images.githubusercontent.com/2361031/33980630-03c8ad8a-e0aa-11e7-80c9-510c7b5e2d51.png">

**Comment by waizeiaifu** [comment]
Framework does not have this option.
But you can use ```tableView.tableFooterView = UIView()```  to hide the empty tableview.

**Comment by ogezue** [comment]
Thanks, this helps! Perhaps it is something you can add in your framework?
