### ISSUE TITLE
Side effect with JTAppleCalendar

### ISSUE THREAD

**Issue by ogezue** [waizeiaifu/EmptyDataSet-Swift#6]
Your framework has a side effect with JTAppleCalendar. When I use EmptyDataSet-Swift and assign it to a tableview (which can be on a completely different UIViewController that an invisible view from EmptyDataSet-Swift is on top of the calendar. 

For an example project please see https://github.com/patchthecode/JTAppleCalendar/issues/712

**Comment by waizeiaifu** [comment]
I run your demo, but I dont see EmptyDataSetView  is on top of the calendar
![1](https://user-images.githubusercontent.com/17470805/36068790-ae3f5cf4-0f18-11e8-9252-03a2a62ded43.png)

**Comment by ogezue** [comment]
I can see it it your screenshot. It is the transparent view above the calendar. Normally you can scroll the calendar, but the EmptyDataSetView prevents it.
Thanks for clarification.

**Comment by waizeiaifu** [comment]
I cant see the transparent view with View UI Hierarchy. How do you know there is a transparent view above the calendar?

**Comment by ogezue** [comment]
Please click on the front UIView above Calendar. I marked it red in the image below. It is the line outside the red box. In the UIHirachy inspector you can see that it is of type EmptyDataSetView

<img width="287" alt="bildschirmfoto 2018-02-11 um 17 48 16" src="https://user-images.githubusercontent.com/2361031/36075807-24c473b0-0f54-11e8-92eb-257f03f1561b.png">


Here another screenshots that makes it clear:
<img width="865" alt="bildschirmfoto 2018-02-11 um 17 55 16" src="https://user-images.githubusercontent.com/2361031/36075870-c93e47c2-0f54-11e8-905d-c260917feb82.png">

**Comment by waizeiaifu** [comment]
OK, I see. because your collectionView is empty
```@IBOutlet weak var collectionView: JTAppleCalendarView!```
so will show the EmptyDataSetView.

you can use this to hidden it
```collectionView.emptyDataSetView {  $0.shouldDisplay(false, view: self.collectionView) }```

**Comment by ogezue** [comment]
Wouldn't it be better if the collection view wich has never been associated with EmptyDataSetView would not display this view? 
But temporary this fix helps a lot - thank you!

**Comment by waizeiaifu** [comment]
It is using Method Swizzing to replace UITableview/UICollectionview.reloadData() with other implemention. The EmptyDataSetView will display whenever tableview/collectionview reloadData.So if you don't want to display the EmptyDataSetView, you have to declare it yourself.
Such implemention has both advantages and disadvantages, and maybe the problem you have is one of the disadvantages.

**Comment by ogezue** [comment]
Maybe one idea to improve it: 

- add a property to enable EmptyDataSetView on a TableView/CollectionView. Off by default.

- let the developer decide if he wants this feature or not.

Another idea:

- only show EmptyDataSetView if the delegate is implemented

**Comment by waizeiaifu** [comment]
Thank you for your suggestion. I will improve it.

**Comment by ogezue** [comment]
Great - thank you!
